import { scoreColor } from './scoreColor'

const width = 1080
const height = 1350
const padding = 84

export const createShareCardFile = async (result) => {
  const score = Math.min(10, Math.max(1, Number(result.overall_score) || 1))
  const tone = scoreColor(score)
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height

  const ctx = canvas.getContext('2d')
  drawCard(ctx, result, score, tone)

  const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png', 0.95))
  if (!blob) throw new Error('Share image could not be created')

  return new File([blob], 'labellens-result.png', { type: 'image/png' })
}

const drawCard = (ctx, result, score, tone) => {
  ctx.fillStyle = '#080808'
  ctx.fillRect(0, 0, width, height)

  drawDots(ctx)
  roundRect(ctx, 42, 42, width - 84, height - 84, 42, '#0F0F0F', '#1E1E1E')

  ctx.fillStyle = '#D4F53C'
  ctx.font = '700 34px Syne, Arial, sans-serif'
  ctx.fillText('LabelLens', padding, 124)

  ctx.fillStyle = '#6B6B6B'
  ctx.font = '500 24px IBM Plex Mono, monospace'
  ctx.fillText('SEE BEYOND THE LABEL', padding, 164)

  ctx.fillStyle = '#EDEDED'
  ctx.font = '700 54px Syne, Arial, sans-serif'
  fillWrappedText(ctx, cleanText(result.product_name || 'Food label'), padding, 258, 760, 64, 2)

  drawScoreRing(ctx, 540, 470, 150, score, tone.text)

  ctx.fillStyle = tone.text
  ctx.font = '500 118px IBM Plex Mono, monospace'
  ctx.textAlign = 'center'
  ctx.fillText(score.toFixed(1), 540, 492)
  ctx.fillStyle = '#6B6B6B'
  ctx.font = '600 32px Syne, Arial, sans-serif'
  ctx.fillText('/ 10', 540, 542)
  ctx.fillStyle = tone.text
  ctx.font = '500 34px IBM Plex Mono, monospace'
  ctx.fillText(result.score_label || tone.label, 540, 650)
  ctx.textAlign = 'left'

  ctx.fillStyle = '#EDEDED'
  ctx.font = 'italic 40px Instrument Serif, Georgia, serif'
  fillWrappedText(ctx, quote(cleanText(result.verdict || 'Nutrition result generated by LabelLens.')), padding, 710, width - padding * 2, 54, 3)

  drawBreakdown(ctx, result.breakdown || {}, 910)

  ctx.fillStyle = '#6B6B6B'
  ctx.font = '500 26px Syne, Arial, sans-serif'
  fillWrappedText(ctx, cleanText(result.recommendation || 'Scan food labels in seconds.'), padding, 1218, width - padding * 2, 38, 2)

  ctx.fillStyle = '#D4F53C'
  ctx.font = '700 30px Syne, Arial, sans-serif'
  ctx.fillText('labellens.app', padding, 1268)
}

const drawBreakdown = (ctx, breakdown, y) => {
  const rows = [
    ['Sugar', breakdown.sugar],
    ['Protein', breakdown.protein],
    ['Fiber', breakdown.fiber],
    ['Additives', breakdown.additives],
    ['Sodium', breakdown.sodium],
  ]

  ctx.fillStyle = '#D4F53C'
  ctx.font = '500 24px IBM Plex Mono, monospace'
  ctx.fillText('BREAKDOWN', padding, y)

  rows.forEach(([label, item = {}], index) => {
    const top = y + 58 + index * 54
    const score = Math.min(10, Math.max(1, Number(item.score) || 5))
    const color = scoreColor(score).text
    const barX = 250
    const barWidth = 560

    ctx.fillStyle = '#EDEDED'
    ctx.font = '700 28px Syne, Arial, sans-serif'
    ctx.fillText(label, padding, top)

    roundRect(ctx, barX, top - 20, barWidth, 14, 7, '#1E1E1E')
    roundRect(ctx, barX, top - 20, (barWidth * score) / 10, 14, 7, color)

    ctx.fillStyle = color
    ctx.font = '500 24px IBM Plex Mono, monospace'
    ctx.fillText(score.toFixed(1), 844, top + 2)

    ctx.fillStyle = '#6B6B6B'
    ctx.font = '500 22px Syne, Arial, sans-serif'
    ctx.fillText(`${item.level || 'Medium'} amount`, 920, top + 2)
  })
}

const drawScoreRing = (ctx, x, y, radius, score, color) => {
  ctx.lineWidth = 16
  ctx.lineCap = 'round'
  ctx.strokeStyle = '#1E1E1E'
  ctx.beginPath()
  ctx.arc(x, y, radius, 0, Math.PI * 2)
  ctx.stroke()

  ctx.strokeStyle = color
  ctx.beginPath()
  ctx.arc(x, y, radius, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * (score / 10))
  ctx.stroke()
}

const drawDots = (ctx) => {
  ctx.fillStyle = '#1E1E1E'
  for (let x = 0; x < width; x += 34) {
    for (let y = 0; y < height; y += 34) {
      ctx.fillRect(x, y, 2, 2)
    }
  }
}

const roundRect = (ctx, x, y, w, h, r, fill, stroke) => {
  ctx.beginPath()
  ctx.moveTo(x + r, y)
  ctx.arcTo(x + w, y, x + w, y + h, r)
  ctx.arcTo(x + w, y + h, x, y + h, r)
  ctx.arcTo(x, y + h, x, y, r)
  ctx.arcTo(x, y, x + w, y, r)
  ctx.closePath()
  if (fill) {
    ctx.fillStyle = fill
    ctx.fill()
  }
  if (stroke) {
    ctx.strokeStyle = stroke
    ctx.lineWidth = 2
    ctx.stroke()
  }
}

const fillWrappedText = (ctx, text, x, y, maxWidth, lineHeight, maxLines = 3) => {
  const words = text.split(/\s+/)
  const lines = []
  let line = ''

  for (const word of words) {
    const next = line ? `${line} ${word}` : word
    if (ctx.measureText(next).width <= maxWidth) {
      line = next
    } else {
      if (line) lines.push(line)
      line = word
    }
    if (lines.length === maxLines) break
  }

  if (line && lines.length < maxLines) lines.push(line)
  lines.forEach((value, index) => ctx.fillText(value, x, y + index * lineHeight))
}

const cleanText = (value) => String(value).replace(/\s+/g, ' ').trim()

const quote = (value) => {
  if (!value) return ''
  return `"${value.replace(/^"+|"+$/g, '')}"`
}
